spring.application.name=crud
spring.datasource.url=${mysql_url}
spring.datasource.username=${mysql_user}
spring.datasource.password=${'mysql_pass'}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql:true
spring.jpa.hibernate.ddl-auto=create
#spring.datasource.url=${MYSQL_URL}
#spring.datasource.username=${MYSQL_USER}
#spring.datasource.password=${MYSQL_PASS}